/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7b745a6f17615c56387f103513bf64bc)
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/server");
		durableNamespaces: "SceneAgent" | "GalleryAgent";
	}
	interface Env {
		AUDIO_BUCKET: R2Bucket;
		AUTH_DB: D1Database;
		AI: Ai;
		ELEVENLABS_API_KEY: string;
		GOOGLE_CLIENT_ID: string;
		GOOGLE_CLIENT_SECRET: string;
		BETTER_AUTH_SECRET: string;
		SceneAgent: DurableObjectNamespace<import("./src/server").SceneAgent>;
		GalleryAgent: DurableObjectNamespace<import("./src/server").GalleryAgent>;
	}
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ELEVENLABS_API_KEY" | "GOOGLE_CLIENT_ID" | "GOOGLE_CLIENT_SECRET" | "BETTER_AUTH_SECRET">> {}
}
