/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false`
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/server");
    durableNamespaces: "SceneAgent" | "GalleryAgent";
  }
  interface Env {
    AUDIO_BUCKET: R2Bucket;
    AI: Ai;
    ELEVENLABS_API_KEY: string;
    SceneAgent: DurableObjectNamespace<import("./src/server").SceneAgent>;
    GalleryAgent: DurableObjectNamespace<import("./src/server").GalleryAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<Pick<Cloudflare.Env, "ELEVENLABS_API_KEY">> {}
}
