/* eslint-disable */
// Generated by Wrangler by running `wrangler types env.d.ts --include-runtime false` (hash: 7b745a6f17615c56387f103513bf64bc)
declare namespace Cloudflare {
  interface GlobalProps {
    durableNamespaces: "SceneAgent" | "GalleryAgent";
    mainModule: typeof import("./src/server");
  }
  interface Env {
    AI: Ai;
    AUDIO_BUCKET: R2Bucket;
    AUTH_DB: D1Database;
    BETTER_AUTH_SECRET: string;
    ELEVENLABS_API_KEY: string;
    GalleryAgent: DurableObjectNamespace<import("./src/server").GalleryAgent>;
    GOOGLE_CLIENT_ID: string;
    GOOGLE_CLIENT_SECRET: string;
    SceneAgent: DurableObjectNamespace<import("./src/server").SceneAgent>;
  }
}
interface Env extends Cloudflare.Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string
    ? EnvType[Binding]
    : string;
};
declare namespace NodeJS {
  interface ProcessEnv
    extends StringifyValues<
      Pick<
        Cloudflare.Env,
        | "ELEVENLABS_API_KEY"
        | "GOOGLE_CLIENT_ID"
        | "GOOGLE_CLIENT_SECRET"
        | "BETTER_AUTH_SECRET"
      >
    > {}
}
